version: '2'
services:
  web:
    image: abilitic_v2_img:latest
    container_name: abilitic_v2_con
    build: .
    ports:
      - "81:80" # self server : docker side
    environment:
      - wwwroot=https://localhost:81/abilitic_v2/lmscore
      - dataroot=/var/www/moodledata_LMS_2_0
      - DEBUG=true
      - DB_HOST=172.16.15.5
      - DB_DATABASE=abilitic_v2
      - DB_USERNAME=zingHr
      - DB_PASSWORD=Power@004
      - DB_PORT=3306
    volumes:
      - ./:/var/www/html/abilitic_v2/
    restart: unless-stopped